# Generated by Django 3.0.6 on 2020-08-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
