# Generated by Django 3.0.6 on 2020-08-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200808_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Teacher'),
        ),
    ]
