# Generated by Django 3.0.6 on 2020-08-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200808_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='teacher',
        ),
    ]
