# Generated by Django 3.0.6 on 2020-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200808_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=10)),
                ('media', models.FileField(null=True, upload_to='', verbose_name='')),
            ],
        ),
    ]
