# Generated by Django 3.0.6 on 2020-08-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mediafile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='name',
            new_name='title',
        ),
    ]
