# Generated by Django 3.0.8 on 2020-08-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='title',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='std',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Standard'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.FileType'),
        ),
    ]
