# Generated by Django 3.0.6 on 2020-08-08 15:20

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200808_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
